---
- block:

  - name: Include secrets
    include_vars:
      file: secrets.yml
      name: secrets

  - name: Check existing docker secrets
    shell: docker secret ls | awk '{print $2}'
    register: docker_secret

  - name: Save secrets from vault
    shell: "echo {{lookup('hashi_vault','secret=' + item.path + ':' + item.name +' token=' + secrets.token + ' validate_certs=' + vault_cert + ' url=' + vault_addr)|quote}} | docker secret create {{ item.name }} -"
    when: "'{{item.name}}' not in docker_secret.stdout_lines"
    with_items: "{{ secrets.secrets }}"

  when: inventory_hostname in groups['docker_swarm_manager'][0]
  become: yes
