---

# Variables setup
- name: Include os-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# with_indexed_items is required as a workaround for this issue:
# https://github.com/ansible/ansible-modules-core/issues/1178
- name: Install python-pip.
  package:
    name: "{{ item.1 }}"
    state: present
  with_indexed_items: "{{ python_pip_packages }}"
  become: yes

# Setup the vDVS
- include: docker_vdvs.yml
  when: not skip_vdvs

# Setup the Docker Swarm Cluster
- include: swarm_cluster.yml
  when: not skip_swarm

#Create Docker Secrets
- include: docker_secrets.yml
  when: not skip_secrets

#Create Docker Networks
- name: Create networks
  include: docker_networks.yml
  when: not skip_networks
